### ISSUE TITLE
Why my plugin with embedded server is enabled but unable to add?

### ISSUE THREAD

**Issue by mong0520** [Kong/go-pluginserver#45] opened 2021-03-25 09:26 UTC
I developed a `hello-world` plugin with embedded server style, and runs it in kong service v2.3.3.
here is the partial configuration:
```
KONG_PLUGINSERVER_NAMES=hello-world
KONG_PLUGINSERVER_HELLO_WORLD_SOCKET="/usr/local/kong/hello-world.socket"
KONG_PLUGINSERVER_HELLO_WORLD_START_CMD="/usr/local/bin/hello-world"
KONG_PLUGINSERVER_HELLO_WORLD_QUERY_CMD="/usr/local/bin/hello-world -dump"
KONG_PLUGINS=bundled
```

here is the partial start up logs:
```
2021/03/25 09:02:11 [debug] 38#0: *1 [kong] process.lua:61 search config for pluginserver named: hello-world
2021/03/25 09:02:11 [notice] 38#0: *18 [kong] process.lua:239 Starting hello-world, context: ngx.timer
2021/03/25 09:02:11 [info] 38#0: *18 [hello-world:46] 2021/03/25 09:02:11 Listening on socket: /usr/local/kong/hello-world.socket, context: ngx.timer
```

I also found the socket file is created `/usr/local/kong/hello-world.socket`, and the plugin executable runs well.
```
/usr/local/bin/hello-world -dump
[{"Name":"hello-world","Phases":["access"],"Version":"1.0.0","Priority":100,"Schema":{"fields":[{"config":{"type":"record","fields":[{"message":{"type":"string"}}]}}],"name":"hello-world"}}]
```

Then I run `curl http://localhost:8001 | jq | grep hello` and the the output below:

```
 "pluginserver_go_plugins_socket": "/usr/local/kong/hello-world.socket",
    "pluginserver_go_plugins_query_cmd": "/usr/local/bin/hello-world -dump",
    "pluginserver_go_plugins_start_cmd": "/usr/local/bin/hello-world",
pluginserver_names": [
      "hello-world"
    ],
```

But why I cannot unable to add this plugin to a service?
```
curl --request POST \
  --url http://localhost:8001/services/hello-service3/plugins \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "hello-world",
	"config": {
		"message": "hello"
	},
	"protocols": ["http"]
}'
```

```
{
  "message": "schema violation (name: plugin 'hello-world' not enabled; add it to the 'plugins' configuration property)",
  "name": "schema violation",
  "fields": {
    "name": "plugin 'hello-world' not enabled; add it to the 'plugins' configuration property"
  },
  "code": 2
}
```

Also, i got empty plugin in the list
```
 > curl http://localhost:8001/plugins
{"next":null,"data":[]}
```

Can anyone help me?

**Comment by fffonion** [comment] 2021-03-25 09:33
Hi @mong0520 you will need to add the plugin name to `plugins`, like a Lua plugin it will to be enabled in kong before
use:
```
KONG_PLUGINS=bundled,hello-world
```

**Comment by mong0520** [comment] 2021-03-25 09:41
@fffonion 

Appreciated, and I also make another mistake

Incorrect:
```
KONG_PLUGINSERVER_GO_PLUGINS_SOCKET="/usr/local/kong/hello-world.socket"
KONG_PLUGINSERVER_GO_PLUGINS_START_CMD="/usr/local/bin/hello-world"
KONG_PLUGINSERVER_GO_PLUGINS_QUERY_CMD="/usr/local/bin/hello-world -dump"
```

Correct:
```
KONG_PLUGINSERVER_HELLO_WORLD_SOCKET="/usr/local/kong/hello-world.socket"
KONG_PLUGINSERVER_HELLO_WORLD_START_CMD="/usr/local/bin/hello-world"
KONG_PLUGINSERVER_HELLO_WORLD_QUERY_CMD="/usr/local/bin/hello-world -dump"
```

Now it works, thank you.

> Hi @mong0520 you will need to add the plugin name to `plugins`, like a Lua plugin it will to be enabled in kong before
> use:
> 
> ```
> KONG_PLUGINS=bundled,hello-world
> ```

**Comment by fffonion** [comment] 2021-03-26 10:45
document added with https://github.com/Kong/docs.konghq.com/pull/2690

**Comment by fffonion** [comment] 2021-04-13 09:25
Closing this as the issue is resolved and docs is now added.

**Closed by fffonion** 2021-04-13 09:25 UTC
Labels: need documentation
